import markdown2
from weasyprint import HTML, CSS

def save_to_pdf(markdown_content, file_name="output.pdf"):
    """
    Save Markdown content to a PDF file with enhanced styling for a more visually appealing output.

    Args:
        markdown_content (str): The Markdown content to be saved.
        file_name (str): Name of the output PDF file.
    """

    # Convert Markdown to HTML
    html_content = markdown2.markdown(markdown_content)

    # Define a more advanced CSS for styling the PDF
    css_content = """
    @page {
        size: A4;
        margin: 20mm;
    }
    body {
        font-family: 'Segoe UI', Arial, sans-serif;
        line-height: 1.8;
        color: #2C3E50;
        margin: 0;
    }
    h1, h2, h3 {
        color: #34495E;
        font-weight: bold;
        margin-bottom: 15px;
    }
    h1 {
        font-size: 28px;
        border-bottom: 2px solid #E74C3C;
        padding-bottom: 5px;
    }
    h2 {
        font-size: 24px;
        border-left: 5px solid #3498DB;
        padding-left: 10px;
    }
    h3 {
        font-size: 20px;
        color: #16A085;
    }
    p {
        margin: 10px 0;
        text-align: justify;
    }
    ul {
        margin: 15px 0;
        padding-left: 25px;
    }
    li {
        margin-bottom: 8px;
    }
    strong {
        color: #E74C3C;
        font-weight: bold;
    }
    code {
        background-color: #F8F9F9;
        padding: 2px 4px;
        border-radius: 4px;
        font-family: 'Courier New', Courier, monospace;
    }
    pre {
        background-color: #F4F6F6;
        padding: 10px;
        border-left: 3px solid #BDC3C7;
        border-radius: 5px;
        overflow-x: auto;
    }
    blockquote {
        margin: 20px 0;
        padding: 15px 20px;
        background-color: #F9F9F9;
        border-left: 5px solid #E67E22;
        font-style: italic;
    }
    footer {
        text-align: center;
        margin-top: 50px;
        font-size: 12px;
        color: #7F8C8D;
    }
    """

    # Add footer for the PDF
    footer = "<footer>Generated by Custom Markdown-to-PDF Converter</footer>"
    full_html_content = f"{html_content}\n{footer}"

    # Convert the HTML content into a PDF
    html = HTML(string=full_html_content)
    css = CSS(string=css_content)
    html.write_pdf(file_name, stylesheets=[css])

    print(f"PDF saved as {file_name}")

# Read Markdown content from 'info.md'
with open("output.md", "r", encoding="utf-8") as file:
    markdown_content = file.read()

# Convert and save as PDF
save_to_pdf(markdown_content, "output.pdf")
